### ISSUE TITLE
查詢繳費代碼的頁面文字需要調整

### ISSUE THREAD

**Issue by yiming330** [yiming330/crossforgod#14]
Need clear description for payment instructions. Can use the same wordings as lifet/makeanegg site.

![5](https://cloud.githubusercontent.com/assets/5311668/7686356/c5196cae-fdc7-11e4-809e-8e2099fc9063.png)

**Comment by yiming330** [comment]
確認了網頁設定是中文, 但pop up 卻顯示英文
![7](https://cloud.githubusercontent.com/assets/5311668/7686808/2213fa52-fdcb-11e4-9a68-64068427f97b.png)

**Comment by yiming330** [comment]
中文的版本, 請加上7-11付款字樣

**Comment by wuboy0307** [comment]
fixed

**Comment by yiming330** [comment]
Confirmed.
