### ISSUE TITLE
送出訂單並未顯示在admin page

### ISSUE THREAD

**Issue by yiming330** [yiming330/crossforgod#3]
送出一筆超商付款訂單. 在admin page -> orders 沒看到
![2](https://cloud.githubusercontent.com/assets/5311668/7685006/2e19297a-fdbd-11e4-8282-22ad4d59c2af.png)

**Comment by wuboy0307** [comment]
fixed for site url problem

**Comment by yiming330** [comment]
Confirmed showing the orders on admin page. Issue closed.
